### ISSUE TITLE
ERROR: become_user is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by BackIsBachus** [RocketChat/Rocket.Chat.Ansible#2]
Hello,

I tried to deploy RocketChat on Debian Jessie using Ansible but when I run my playbook (which is the one used in your README) I get the following output:
```
 [WARNING]: It is unnecessary to use '{{' in loops, leave variables in loop
expressions bare.

ERROR: become_user is not a legal parameter in an Ansible task or handler
```
I am trying to install it on localhost (since it's just as a test), and I already managed to run a few simple playbooks on localhost before.
I have installed Ansible from the deb package manager so I am in 1.7.2 (I am quite new to Ansible too so it may also be an Ansible problem from my side unrelated to this).

Thanks!

**Comment by cmacrae** [comment]
Hey! Thanks for taking the time to raise this issue.  
The reason you're seeing this problem is because your Ansible version is too old.
The `become` module was [introduced in Ansible 1.9.4](http://docs.ansible.com/ansible/become.html) - which is the version you should be running.  

See [Ansible's installation documentation](http://docs.ansible.com/ansible/intro_installation.html) to get 1.9.4 installed :+1:

**Comment by gneutzling** [comment]
I had this problema and I did an upgrade to `ansible 1.9.2` with using homebrew and worked fine.

**Comment by cmacrae** [comment]
@gneutzling Ansible 1.9.4 is still the minimum version required to run the Ansible 1 version of this code.
