### ISSUE TITLE
Upgrade fails when latest download already exists

### ISSUE THREAD

**Issue by rwarsing** [RocketChat/Rocket.Chat.Ansible#25]
Upgrading will fail if the 'rocket.chat-0.X.0.tgz' file has been previously downloaded but not applied.

**Comment by cmacrae** [comment]
I'm away on holiday at the moment. I'll take a look at fixing this when I'm back home.

**Comment by jlgore** [comment]
I'm also noticing this, but also noticing if I remove the tarball the playbook fails w/this:

```

TASK [RocketChat.Server : Fetch the Rocket.Chat binary tarball] ****************
changed: [chat]

RUNNING HANDLER [RocketChat.Server : Upgrade Rocket.Chat] **********************
ERROR! Unexpected Exception: 'TaskInclude' object has no attribute 'has_triggered'
```

**Comment by PeterMosmans** [comment]
The Upgrade Rocket.Chat handler seems to be b0rked if no previous version has been installed.
Quick and dirty hack for the above problem: Remark line 96 of `tasks/main.yml` (notify: Upgrade Rocket.Chat)

**Comment by jlgore** [comment]
I've been able to update this particular instance a few times before, but for some reason I can't move this install past 0.33.0 at all. I tried commenting out line 96 like you mentioned but it still doesn't upgrade. It will fetch the 0.35.0 tgz just fine, but skips the unpacking stage.

`TASK [RocketChat.Server : Fetch the Rocket.Chat binary tarball] ****************
changed: [rc.shifthosting.dc.nolasecure.it]

TASK [RocketChat.Server : Unpack the Rocket.Chat binary tarball] ***************
skipping: [rc.shifthosting.dc.nolasecure.it]

TASK [RocketChat.Server : Install Rocket.Chat via NPM] *************************
ok: [rc.shifthosting.dc.nolasecure.it]`

If there's anything else I can try to test or help please let me know.

**Comment by xenithorb** [comment]
#26 fixes this

**Comment by jlgore** [comment]
Hi @xenithorb I downloaded the latest from Galaxy and ran it on my instance that won't update. I get this when I run the playbook now:

`TASK [RocketChat.Server : Fetch the Rocket.Chat binary tarball] ****************
ERROR! The requested handler 'Upgrade Rocket.Chat' was not found in any of the known handlers`

Any ideas? Thanks!

**Comment by xenithorb** [comment]
That's a separate issue and it should have been fixed by: https://github.com/RocketChat/Rocket.Chat.Ansible/commit/fd90707b12e7a1a0868a50e971f00194c87e3547

Don't forget that if you've pinned the version, you need to move that in your own playbook - i.e. `v2.0` should now be `v2.1.1`

If you want the latest version each time, use the `master` branch now, as I rebased that against v2.0 a few days ago. I wish I had a better way to announce that, I suppose I could bold something on the top of the README for a bit.

**Comment by xenithorb** [comment]
Additionally, a great way of checking on the version is looking at: https://galaxy.ansible.com/RocketChat/Server/ the most recent tag will be at the top

**Comment by jlgore** [comment]
THANK YOU SO MUCH. My hero. When I get paid I'm donating to the project again, you guys are doing the work!

**Comment by xenithorb** [comment]
Going to merge #28 once the build completes (silly to have to do that for README but it is what it is), hopefully that helps with some confusion.

**Comment by xenithorb** [comment]
OK. So the situation has changed here a bit, there are now three possible states (as soon as the builds pass and I get 5e11c0a  and  bcc487c merged into master) 

1.  With "new feature" `rocket_chat_tarball_check_checksum == false` the checksum is `omit`ted AND the `force:` parameter to `get_url` is set to `yes`, AND the result is always changed alert the following task that checks for `result|changed`. This effectively means it will download and overwrite the tarball at all costs. 

2. With `rocket_chat_tarball_check_checksum == true` (the default still for security) - the `checksum: ` parameter to `get_url` checks the file's hash and if it's different it downloads the file again, and reports as changed. So if you change the checksum manually, and the file doesn't match locally, it will overwrite it in an attempt to "find" the right file remotely. 

3. The third and still "bad" state is when something goes wrong with #2 within the `upgrade.yml` file, if that condition occurs, the correct file has been downloaded but the RC server hasn't been upgraded properly, and I need to think a little more about that. Currently to rectify that, consider just deleting the remote tarball so that it forced the play to download it over again and continue the upgrade process.
