### ISSUE TITLE
Fix travis builds so that they actually work again

### ISSUE THREAD

**Issue by nickbroon** [RocketChat/Rocket.Chat.Ansible#66]
Makes validating Pull Request non trivial.
Either all jobs should pass or if failures are expected `allow_failures` used.

**Comment by xenithorb** [comment]
What's not trivial is writing a complex role such as this and getting it to not fail when run in docker containers :'( 

I'll work on it soon

**Comment by xenithorb** [comment]
The biggest problems seem to stem from the multitude of dependency systems used throughout the play. (i.e. if it's usually pip or npm dying on some external dependency mess up)

Example:

```
----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-Qb_G_C/cryptography
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 70: ordinal not in range(128)
The command '/bin/sh -c pip install --upgrade ansible' returned a non-zero code: 1
The command "sudo docker build --rm=true --file="tests/Dockerfile.${dist}-${ver}" --tag="${dist}:ansible" tests" failed and exited with 1 during .
```

This has absolutely nothing to do with even getting to the ansible playbook yet - it's failing on even installing ansible to run the damn playbook against itself!

And, I had originally switched away from using the local package manager's version of ansible because it's oft not recommended to use those old versions (like say on debian or ubuntu LTS) because ansible is an extremely fast-moving project with lots of bug fixes. 

Since I'm not really sure where my target audience lies I tend to try and stay current with requiring recent (but not necessarily latest) versions of ansible. 

Probably going to drop support for the old Ubuntu version, _maybe_ Deb 8 now that 9 is out... and we need to start testing on newer distros too, like Fedora 27, 28 ... I'd even like to get Rawhide in there, CentOS needs to be checked again 7.4 now.

**Comment by xenithorb** [comment]
Hmm, maybe we can standardize the ansible version across containers by using Docker-In-Docker and pull in and use a reliable container with ansible pre-installed?

**Comment by lossos** [comment]
I added a PR #108 which does provide a very simple, but working travis config for running the playbook inside docker. This one still need some improvement (e.g. additional tests at the end). Ubuntu 18.04 is also always failing because it does use the debian variables and i didn't figured out tonight why it does that.
