### ISSUE TITLE
Ensure provided PFS key has been deployed FAIL

### ISSUE THREAD

**Issue by golimer** [RocketChat/Rocket.Chat.Ansible#85]
TASK [Rocket.Chat.Ansible : Ensure provided PFS key has been deployed] 
fatal: [172.31.11.21]: FAILED! => {"changed": false, "failed": true, "msg": "src (or content) is required"}

any suggestions?

**Comment by haffla** [comment]
I can confirm this. I believe the problem is here https://github.com/RocketChat/Rocket.Chat.Ansible/blob/develop/tasks/nginx.yml#L74

In `defaults/main.yml` `rocket_chat_nginx_pfs_file` is actually defined as `~`.

So this `copy` task tries to copy `~` which is of course not a file. Uncommenting `rocket_chat_nginx_pfs_file` in `defaults/main.yml` fixes this.

**Comment by haffla** [comment]
Hello! Could you inform why this issue was closed? I just ran into this myself....
